---

- hosts: all
  become: true
  tasks:

  - name: install apache server
    apt:
      name: apache2

  - name: update cache
    apt:
      update_cache:  yes
    when: ansible_distribution == "ubuntu"


